[build]
  publish = "/"
  command = ""

# Force cache clearing with each deployment
[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_CACHE_BUST = "true"

# Redirect all page URLs to the appropriate HTML files
[[redirects]]
  from = "/products"
  to = "/products.html"
  status = 200

[[redirects]]
  from = "/product-details"
  to = "/product-details.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

# Handle product detail pages with IDs
[[redirects]]
  from = "/product-details/*"
  to = "/product-details.html?id=:splat"
  status = 200

# This needs to be last - fallback for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add headers for security and proper caching control
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, max-age=0, must-revalidate"

# Cache assets for better performance but with proper validation
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
